/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Land;

/**
 *
 * @author Sandu
 */
public class sample extends javax.swing.JFrame {

    /**
     * Creates new form sample
     */
    public sample() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P1_3_Ins = new javax.swing.JPanel();
        P1_3_Ins_L1 = new javax.swing.JLabel();
        P1_3_Ins_C1 = new javax.swing.JComboBox();
        P1_3_Ins_L2 = new javax.swing.JLabel();
        P1_3_Ins_C2 = new javax.swing.JComboBox();
        P1_3_Ins_1 = new javax.swing.JPanel();
        P1_3_Ins_1_L1 = new javax.swing.JLabel();
        P1_3_Ins_1_L8 = new javax.swing.JLabel();
        P1_3_Ins_1_T1 = new javax.swing.JTextField();
        P1_3_Ins_1_R2 = new javax.swing.JRadioButton();
        P1_3_Ins_1_L3 = new javax.swing.JLabel();
        P1_3_Ins_1_L10 = new javax.swing.JLabel();
        P1_3_Ins_1_T3 = new javax.swing.JTextField();
        P1_3_Ins_2 = new javax.swing.JPanel();
        P1_3_Ins_2_L1 = new javax.swing.JLabel();
        P1_3_Ins_2_T1 = new javax.swing.JTextField();
        P1_3_Ins_2_L2 = new javax.swing.JLabel();
        P1_3_Ins_2_T2 = new javax.swing.JTextField();
        P1_3_Ins_2_L3 = new javax.swing.JLabel();
        P1_3_Ins_2_T3 = new javax.swing.JTextField();
        P1_3_Ins_2_L4 = new javax.swing.JLabel();
        P1_3_Ins_2_T4 = new javax.swing.JTextField();
        P1_3_Ins_3 = new javax.swing.JPanel();
        P1_3_Ins_3_L3 = new javax.swing.JLabel();
        P1_3_Ins_3_T3 = new javax.swing.JTextField();
        P1_3_Ins_3_C1 = new javax.swing.JComboBox();
        P1_3_Ins_3_L5 = new javax.swing.JLabel();
        P1_3_Ins_C3 = new javax.swing.JComboBox();
        P1_3_Ins_L3 = new javax.swing.JLabel();
        Sep_Ins = new javax.swing.JSeparator();
        BC_Ins = new javax.swing.JLabel();
        P1_3_Ins_STR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        P1_3_Ins.setOpaque(false);
        P1_3_Ins.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P1_3_Ins_L1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        P1_3_Ins_L1.setForeground(new java.awt.Color(204, 204, 204));
        P1_3_Ins_L1.setText("District");
        P1_3_Ins.add(P1_3_Ins_L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        P1_3_Ins_C1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "      ---Select---", " " }));
        P1_3_Ins.add(P1_3_Ins_C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 180, -1));

        P1_3_Ins_L2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        P1_3_Ins_L2.setForeground(new java.awt.Color(204, 204, 204));
        P1_3_Ins_L2.setText("G.N Division");
        P1_3_Ins.add(P1_3_Ins_L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        P1_3_Ins_C2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "       ---Select---" }));
        P1_3_Ins.add(P1_3_Ins_C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 197, -1));

        P1_3_Ins_1.setBackground(new java.awt.Color(66, 36, 132));

        P1_3_Ins_1_L1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        P1_3_Ins_1_L1.setForeground(new java.awt.Color(204, 204, 204));
        P1_3_Ins_1_L1.setText("Name of the Department");

        P1_3_Ins_1_L8.setForeground(new java.awt.Color(255, 0, 0));
        P1_3_Ins_1_L8.setText("*");

        P1_3_Ins_1_R2.setBackground(new java.awt.Color(66, 36, 132));
        P1_3_Ins_1_R2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        P1_3_Ins_1_R2.setForeground(new java.awt.Color(204, 204, 204));
        P1_3_Ins_1_R2.setText("No");

        P1_3_Ins_1_L3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        P1_3_Ins_1_L3.setForeground(new java.awt.Color(204, 204, 204));
        P1_3_Ins_1_L3.setText("Department Address");

        P1_3_Ins_1_L10.setForeground(new java.awt.Color(255, 0, 0));
        P1_3_Ins_1_L10.setText("*");

        javax.swing.GroupLayout P1_3_Ins_1Layout = new javax.swing.GroupLayout(P1_3_Ins_1);
        P1_3_Ins_1.setLayout(P1_3_Ins_1Layout);
        P1_3_Ins_1Layout.setHorizontalGroup(
            P1_3_Ins_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1_3_Ins_1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(P1_3_Ins_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(P1_3_Ins_1_L3)
                    .addComponent(P1_3_Ins_1_L1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P1_3_Ins_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P1_3_Ins_1_L8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_3_Ins_1_L10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(P1_3_Ins_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P1_3_Ins_1_T3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P1_3_Ins_1Layout.createSequentialGroup()
                        .addComponent(P1_3_Ins_1_T1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)))
                .addGap(212, 212, 212)
                .addComponent(P1_3_Ins_1_R2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P1_3_Ins_1Layout.setVerticalGroup(
            P1_3_Ins_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1_3_Ins_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P1_3_Ins_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3_Ins_1_L1)
                    .addComponent(P1_3_Ins_1_L8)
                    .addComponent(P1_3_Ins_1_T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(P1_3_Ins_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P1_3_Ins_1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P1_3_Ins_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P1_3_Ins_1_R2)
                            .addComponent(P1_3_Ins_1_L3)
                            .addComponent(P1_3_Ins_1_L10)))
                    .addGroup(P1_3_Ins_1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(P1_3_Ins_1_T3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        P1_3_Ins.add(P1_3_Ins_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 820, -1));

        P1_3_Ins_2.setBackground(new java.awt.Color(66, 36, 132));

        P1_3_Ins_2_L1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        P1_3_Ins_2_L1.setForeground(new java.awt.Color(204, 204, 204));
        P1_3_Ins_2_L1.setText("Mobile");

        P1_3_Ins_2_L2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        P1_3_Ins_2_L2.setForeground(new java.awt.Color(204, 204, 204));
        P1_3_Ins_2_L2.setText("Telephone");

        P1_3_Ins_2_L3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        P1_3_Ins_2_L3.setForeground(new java.awt.Color(204, 204, 204));
        P1_3_Ins_2_L3.setText("E Mail");

        P1_3_Ins_2_L4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        P1_3_Ins_2_L4.setForeground(new java.awt.Color(204, 204, 204));
        P1_3_Ins_2_L4.setText("Fax");

        javax.swing.GroupLayout P1_3_Ins_2Layout = new javax.swing.GroupLayout(P1_3_Ins_2);
        P1_3_Ins_2.setLayout(P1_3_Ins_2Layout);
        P1_3_Ins_2Layout.setHorizontalGroup(
            P1_3_Ins_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1_3_Ins_2Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addGroup(P1_3_Ins_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(P1_3_Ins_2_L4)
                    .addComponent(P1_3_Ins_2_L3)
                    .addComponent(P1_3_Ins_2_L2)
                    .addComponent(P1_3_Ins_2_L1))
                .addGap(32, 32, 32)
                .addGroup(P1_3_Ins_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(P1_3_Ins_2_T2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(P1_3_Ins_2_T1)
                    .addComponent(P1_3_Ins_2_T3)
                    .addComponent(P1_3_Ins_2_T4))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        P1_3_Ins_2Layout.setVerticalGroup(
            P1_3_Ins_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1_3_Ins_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P1_3_Ins_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3_Ins_2_L1)
                    .addComponent(P1_3_Ins_2_T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P1_3_Ins_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3_Ins_2_L2)
                    .addComponent(P1_3_Ins_2_T2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P1_3_Ins_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3_Ins_2_L3)
                    .addComponent(P1_3_Ins_2_T3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(P1_3_Ins_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3_Ins_2_T4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_3_Ins_2_L4))
                .addContainerGap())
        );

        P1_3_Ins.add(P1_3_Ins_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 820, 130));

        P1_3_Ins_3.setBackground(new java.awt.Color(66, 36, 132));

        P1_3_Ins_3_L3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        P1_3_Ins_3_L3.setForeground(new java.awt.Color(204, 204, 204));
        P1_3_Ins_3_L3.setText("Prefferd Method of Communication");

        P1_3_Ins_3_C1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "        ---Select---" }));

        P1_3_Ins_3_L5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        P1_3_Ins_3_L5.setForeground(new java.awt.Color(204, 204, 204));
        P1_3_Ins_3_L5.setText("Language of Communication");

        javax.swing.GroupLayout P1_3_Ins_3Layout = new javax.swing.GroupLayout(P1_3_Ins_3);
        P1_3_Ins_3.setLayout(P1_3_Ins_3Layout);
        P1_3_Ins_3Layout.setHorizontalGroup(
            P1_3_Ins_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P1_3_Ins_3Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(P1_3_Ins_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(P1_3_Ins_3_L5)
                    .addComponent(P1_3_Ins_3_L3))
                .addGap(33, 33, 33)
                .addGroup(P1_3_Ins_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(P1_3_Ins_3_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_3_Ins_3_T3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        P1_3_Ins_3Layout.setVerticalGroup(
            P1_3_Ins_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1_3_Ins_3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P1_3_Ins_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3_Ins_3_L5)
                    .addComponent(P1_3_Ins_3_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P1_3_Ins_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3_Ins_3_T3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_3_Ins_3_L3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        P1_3_Ins.add(P1_3_Ins_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 820, 80));

        P1_3_Ins_C3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "       ---Select---", " " }));
        P1_3_Ins_C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1_3_Ins_C3ActionPerformed(evt);
            }
        });
        P1_3_Ins.add(P1_3_Ins_C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 177, -1));

        P1_3_Ins_L3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        P1_3_Ins_L3.setForeground(new java.awt.Color(204, 204, 204));
        P1_3_Ins_L3.setText("D.S Division");
        P1_3_Ins.add(P1_3_Ins_L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, 20));
        P1_3_Ins.add(Sep_Ins, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 950, 10));

        BC_Ins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Land/Images/panel.png"))); // NOI18N
        BC_Ins.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        P1_3_Ins.add(BC_Ins, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 410));

        P1_3_Ins_STR.setForeground(new java.awt.Color(255, 0, 0));
        P1_3_Ins_STR.setText("*");
        P1_3_Ins.add(P1_3_Ins_STR, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 24, 10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(P1_3_Ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(P1_3_Ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P1_3_Ins_C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1_3_Ins_C3ActionPerformed

    }//GEN-LAST:event_P1_3_Ins_C3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sample().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BC_Ins;
    private javax.swing.JPanel P1_3_Ins;
    private javax.swing.JPanel P1_3_Ins_1;
    private javax.swing.JLabel P1_3_Ins_1_L1;
    private javax.swing.JLabel P1_3_Ins_1_L10;
    private javax.swing.JLabel P1_3_Ins_1_L3;
    private javax.swing.JLabel P1_3_Ins_1_L8;
    private javax.swing.JRadioButton P1_3_Ins_1_R2;
    private javax.swing.JTextField P1_3_Ins_1_T1;
    private javax.swing.JTextField P1_3_Ins_1_T3;
    private javax.swing.JPanel P1_3_Ins_2;
    private javax.swing.JLabel P1_3_Ins_2_L1;
    private javax.swing.JLabel P1_3_Ins_2_L2;
    private javax.swing.JLabel P1_3_Ins_2_L3;
    private javax.swing.JLabel P1_3_Ins_2_L4;
    private javax.swing.JTextField P1_3_Ins_2_T1;
    private javax.swing.JTextField P1_3_Ins_2_T2;
    private javax.swing.JTextField P1_3_Ins_2_T3;
    private javax.swing.JTextField P1_3_Ins_2_T4;
    private javax.swing.JPanel P1_3_Ins_3;
    private javax.swing.JComboBox P1_3_Ins_3_C1;
    private javax.swing.JLabel P1_3_Ins_3_L3;
    private javax.swing.JLabel P1_3_Ins_3_L5;
    private javax.swing.JTextField P1_3_Ins_3_T3;
    private javax.swing.JComboBox P1_3_Ins_C1;
    private javax.swing.JComboBox P1_3_Ins_C2;
    private javax.swing.JComboBox P1_3_Ins_C3;
    private javax.swing.JLabel P1_3_Ins_L1;
    private javax.swing.JLabel P1_3_Ins_L2;
    private javax.swing.JLabel P1_3_Ins_L3;
    private javax.swing.JLabel P1_3_Ins_STR;
    private javax.swing.JSeparator Sep_Ins;
    // End of variables declaration//GEN-END:variables
}
