
public class NewYear extends javax.swing.JFrame {

    /**
     * Creates new form NewYear
     */
    public NewYear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P1_3 = new javax.swing.JPanel();
        P1_3_L1 = new javax.swing.JLabel();
        P1_3_R1 = new javax.swing.JRadioButton();
        P1_3_R2 = new javax.swing.JRadioButton();
        P1_3_L3 = new javax.swing.JLabel();
        P1_3_L2 = new javax.swing.JLabel();
        P1_3_C2 = new javax.swing.JComboBox();
        P1_3_C1 = new javax.swing.JComboBox();
        P1_3_C3 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        P1_3_STR = new javax.swing.JLabel();
        P1_3_1 = new javax.swing.JPanel();
        P1_3_1_L1 = new javax.swing.JLabel();
        P1_3_1_L8 = new javax.swing.JLabel();
        P1_3_1_T1 = new javax.swing.JTextField();
        P1_3_1_L2 = new javax.swing.JLabel();
        P1_3_1_L9 = new javax.swing.JLabel();
        P1_3_1_T2 = new javax.swing.JTextField();
        P1_3_1_L6 = new javax.swing.JLabel();
        P1_3_1_R3 = new javax.swing.JRadioButton();
        P1_3_1_R4 = new javax.swing.JRadioButton();
        P1_3_1_L13 = new javax.swing.JLabel();
        P1_3_1_L4 = new javax.swing.JLabel();
        P1_3_1_L11 = new javax.swing.JLabel();
        P1_3_1_T4 = new javax.swing.JTextField();
        P1_3_1_L5 = new javax.swing.JLabel();
        P1_3_1_L12 = new javax.swing.JLabel();
        P1_3_1_L14 = new javax.swing.JLabel();
        P1_3_1_R1 = new javax.swing.JRadioButton();
        P1_3_1_R2 = new javax.swing.JRadioButton();
        P1_3_1_L3 = new javax.swing.JLabel();
        P1_3_1_L10 = new javax.swing.JLabel();
        P1_3_1_T3 = new javax.swing.JTextField();
        P1_3_2 = new javax.swing.JPanel();
        P1_3_2_L1 = new javax.swing.JLabel();
        P1_3_2_T1 = new javax.swing.JTextField();
        P1_3_2_L2 = new javax.swing.JLabel();
        P1_3_2_T2 = new javax.swing.JTextField();
        P1_3_2_L3 = new javax.swing.JLabel();
        P1_3_2_T3 = new javax.swing.JTextField();
        P1_3_2_L4 = new javax.swing.JLabel();
        P1_3_2_T4 = new javax.swing.JTextField();
        P1_3_3 = new javax.swing.JPanel();
        P1_3_3_L1 = new javax.swing.JLabel();
        P1_3_3_T1 = new javax.swing.JTextField();
        P1_3_3_L2 = new javax.swing.JLabel();
        P1_3_3_T2 = new javax.swing.JTextField();
        P1_3_3_L3 = new javax.swing.JLabel();
        P1_3_3_T3 = new javax.swing.JTextField();
        P1_3_3_L4 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        P1_3_3_L6 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox();
        P1_3_3_L5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        P1_3_L1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_L1.setText("District");

        P1_3_R1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        P1_3_R1.setText("Person");

        P1_3_R2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        P1_3_R2.setText("Institute");

        P1_3_L3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_L3.setText("D.S Division");

        P1_3_L2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_L2.setText("G.N Division");

        P1_3_C2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "       ---Select---" }));

        P1_3_C1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "      ---Select---", " " }));

        P1_3_C3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "       ---Select---", " " }));
        P1_3_C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1_3_C3ActionPerformed(evt);
            }
        });

        P1_3_STR.setForeground(new java.awt.Color(255, 0, 0));
        P1_3_STR.setText("*");

        P1_3_1_L1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_1_L1.setText("Name");

        P1_3_1_L8.setForeground(new java.awt.Color(255, 0, 0));
        P1_3_1_L8.setText("*");

        P1_3_1_L2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_1_L2.setText("NIC No");

        P1_3_1_L9.setForeground(new java.awt.Color(255, 0, 0));
        P1_3_1_L9.setText("*");

        P1_3_1_L6.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_1_L6.setText("Gender");

        P1_3_1_R3.setText("Male");

        P1_3_1_R4.setText("Female");

        P1_3_1_L13.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        P1_3_1_L13.setForeground(new java.awt.Color(0, 51, 153));
        P1_3_1_L13.setText("(YYYY-MM-DD)");

        P1_3_1_L4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_1_L4.setText("Date of Birth");

        P1_3_1_L11.setForeground(new java.awt.Color(255, 0, 0));
        P1_3_1_L11.setText("*");

        P1_3_1_L5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_1_L5.setText("Nationality");

        P1_3_1_L12.setForeground(new java.awt.Color(255, 0, 0));
        P1_3_1_L12.setText("*");

        P1_3_1_L14.setText("Sri Lankan");

        P1_3_1_R1.setText("Yes");

        P1_3_1_R2.setText("No");

        P1_3_1_L3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_1_L3.setText("Address");

        P1_3_1_L10.setForeground(new java.awt.Color(255, 0, 0));
        P1_3_1_L10.setText("*");

        javax.swing.GroupLayout P1_3_1Layout = new javax.swing.GroupLayout(P1_3_1);
        P1_3_1.setLayout(P1_3_1Layout);
        P1_3_1Layout.setHorizontalGroup(
            P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1_3_1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(P1_3_1_L3)
                    .addComponent(P1_3_1_L2)
                    .addComponent(P1_3_1_L1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(P1_3_1Layout.createSequentialGroup()
                        .addComponent(P1_3_1_L8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(P1_3_1_T1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(P1_3_1_L13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P1_3_1_L4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, P1_3_1Layout.createSequentialGroup()
                        .addGroup(P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P1_3_1_L9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P1_3_1_L10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P1_3_1Layout.createSequentialGroup()
                                .addComponent(P1_3_1_T3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(P1_3_1_L6))
                            .addGroup(P1_3_1Layout.createSequentialGroup()
                                .addComponent(P1_3_1_T2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(P1_3_1_L5)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(P1_3_1Layout.createSequentialGroup()
                        .addComponent(P1_3_1_L11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P1_3_1_T4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P1_3_1Layout.createSequentialGroup()
                        .addComponent(P1_3_1_L12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P1_3_1Layout.createSequentialGroup()
                                .addComponent(P1_3_1_L14)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P1_3_1Layout.createSequentialGroup()
                                .addComponent(P1_3_1_R3)
                                .addGap(46, 46, 46)))
                        .addGroup(P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P1_3_1Layout.createSequentialGroup()
                                .addComponent(P1_3_1_R1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(P1_3_1_R2))
                            .addGroup(P1_3_1Layout.createSequentialGroup()
                                .addComponent(P1_3_1_R4)
                                .addGap(76, 76, 76)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        P1_3_1Layout.setVerticalGroup(
            P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1_3_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3_1_L1)
                    .addComponent(P1_3_1_L8)
                    .addComponent(P1_3_1_T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_3_1_L4)
                    .addComponent(P1_3_1_L11)
                    .addComponent(P1_3_1_L13)
                    .addComponent(P1_3_1_T4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3_1_L2)
                    .addComponent(P1_3_1_L9)
                    .addComponent(P1_3_1_T2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_3_1_L5)
                    .addComponent(P1_3_1_L12)
                    .addComponent(P1_3_1_L14)
                    .addComponent(P1_3_1_R1)
                    .addComponent(P1_3_1_R2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(P1_3_1_R3)
                        .addComponent(P1_3_1_R4)
                        .addComponent(P1_3_1_L6))
                    .addGroup(P1_3_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(P1_3_1_L3)
                        .addComponent(P1_3_1_L10)
                        .addComponent(P1_3_1_T3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        P1_3_2_L1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_2_L1.setText("Mobile");

        P1_3_2_L2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_2_L2.setText("Telephone");

        P1_3_2_L3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_2_L3.setText("E Mail");

        P1_3_2_L4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_2_L4.setText("Fax");

        javax.swing.GroupLayout P1_3_2Layout = new javax.swing.GroupLayout(P1_3_2);
        P1_3_2.setLayout(P1_3_2Layout);
        P1_3_2Layout.setHorizontalGroup(
            P1_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1_3_2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(P1_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P1_3_2_L1)
                    .addComponent(P1_3_2_L2))
                .addGap(38, 38, 38)
                .addGroup(P1_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(P1_3_2_T1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(P1_3_2_T2))
                .addGap(285, 285, 285)
                .addGroup(P1_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(P1_3_2_L3)
                    .addComponent(P1_3_2_L4))
                .addGap(30, 30, 30)
                .addGroup(P1_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(P1_3_2_T3, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(P1_3_2_T4))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        P1_3_2Layout.setVerticalGroup(
            P1_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1_3_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P1_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3_2_L1)
                    .addComponent(P1_3_2_T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_3_2_L3)
                    .addComponent(P1_3_2_T3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P1_3_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3_2_L2)
                    .addComponent(P1_3_2_T2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_3_2_L4)
                    .addComponent(P1_3_2_T4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        P1_3_3_L1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_3_L1.setText("Name of Spouse");

        P1_3_3_L2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_3_L2.setText("Occupation");

        P1_3_3_L3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_3_L3.setText("Prefferd Method of Communication");

        P1_3_3_L4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_3_L4.setText("Annual Income of the family");

        P1_3_3_L6.setForeground(new java.awt.Color(255, 0, 0));
        P1_3_3_L6.setText("*");

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "        ---Select---" }));

        P1_3_3_L5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        P1_3_3_L5.setText("Language of Communication");

        javax.swing.GroupLayout P1_3_3Layout = new javax.swing.GroupLayout(P1_3_3);
        P1_3_3.setLayout(P1_3_3Layout);
        P1_3_3Layout.setHorizontalGroup(
            P1_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P1_3_3Layout.createSequentialGroup()
                .addGroup(P1_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P1_3_3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(P1_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P1_3_3_L2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(P1_3_3_L1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(32, 32, 32))
                    .addGroup(P1_3_3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(P1_3_3_L3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                .addGroup(P1_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P1_3_3_T3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P1_3_3Layout.createSequentialGroup()
                        .addGroup(P1_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(P1_3_3Layout.createSequentialGroup()
                                .addComponent(P1_3_3_T1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154)
                                .addComponent(P1_3_3_L4))
                            .addGroup(P1_3_3Layout.createSequentialGroup()
                                .addComponent(P1_3_3_T2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(P1_3_3_L5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P1_3_3_L6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P1_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
        );
        P1_3_3Layout.setVerticalGroup(
            P1_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1_3_3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P1_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3_3_L4)
                    .addComponent(P1_3_3_L6)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_3_3_T1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_3_3_L1))
                .addGap(18, 18, 18)
                .addGroup(P1_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_3_3_L5)
                    .addComponent(P1_3_3_L2)
                    .addComponent(P1_3_3_T2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(P1_3_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1_3_3_T3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1_3_3_L3))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout P1_3Layout = new javax.swing.GroupLayout(P1_3);
        P1_3.setLayout(P1_3Layout);
        P1_3Layout.setHorizontalGroup(
            P1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1_3Layout.createSequentialGroup()
                .addGroup(P1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P1_3Layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(P1_3_R1)
                        .addGap(27, 27, 27)
                        .addComponent(P1_3_R2))
                    .addGroup(P1_3Layout.createSequentialGroup()
                        .addGap(406, 406, 406)
                        .addComponent(P1_3_L2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P1_3_STR, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(P1_3_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(P1_3_L3)
                        .addGap(24, 24, 24)
                        .addComponent(P1_3_C3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P1_3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(P1_3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(P1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P1_3Layout.createSequentialGroup()
                        .addComponent(P1_3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(P1_3Layout.createSequentialGroup()
                        .addGroup(P1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P1_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P1_3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(P1_3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(P1_3_L1)
                                .addGap(18, 18, 18)
                                .addComponent(P1_3_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        P1_3Layout.setVerticalGroup(
            P1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1_3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(P1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P1_3_R1)
                    .addComponent(P1_3_R2))
                .addGap(18, 18, 18)
                .addGroup(P1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(P1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(P1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P1_3_L2)
                            .addComponent(P1_3_STR)
                            .addComponent(P1_3_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(P1_3Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(P1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(P1_3_L3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(P1_3_C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(P1_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(P1_3_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(P1_3_L1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(P1_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(P1_3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(P1_3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(P1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P1_3_C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1_3_C3ActionPerformed

    }//GEN-LAST:event_P1_3_C3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewYear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewYear().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P1_3;
    private javax.swing.JPanel P1_3_1;
    private javax.swing.JLabel P1_3_1_L1;
    private javax.swing.JLabel P1_3_1_L10;
    private javax.swing.JLabel P1_3_1_L11;
    private javax.swing.JLabel P1_3_1_L12;
    private javax.swing.JLabel P1_3_1_L13;
    private javax.swing.JLabel P1_3_1_L14;
    private javax.swing.JLabel P1_3_1_L2;
    private javax.swing.JLabel P1_3_1_L3;
    private javax.swing.JLabel P1_3_1_L4;
    private javax.swing.JLabel P1_3_1_L5;
    private javax.swing.JLabel P1_3_1_L6;
    private javax.swing.JLabel P1_3_1_L8;
    private javax.swing.JLabel P1_3_1_L9;
    private javax.swing.JRadioButton P1_3_1_R1;
    private javax.swing.JRadioButton P1_3_1_R2;
    private javax.swing.JRadioButton P1_3_1_R3;
    private javax.swing.JRadioButton P1_3_1_R4;
    private javax.swing.JTextField P1_3_1_T1;
    private javax.swing.JTextField P1_3_1_T2;
    private javax.swing.JTextField P1_3_1_T3;
    private javax.swing.JTextField P1_3_1_T4;
    private javax.swing.JPanel P1_3_2;
    private javax.swing.JLabel P1_3_2_L1;
    private javax.swing.JLabel P1_3_2_L2;
    private javax.swing.JLabel P1_3_2_L3;
    private javax.swing.JLabel P1_3_2_L4;
    private javax.swing.JTextField P1_3_2_T1;
    private javax.swing.JTextField P1_3_2_T2;
    private javax.swing.JTextField P1_3_2_T3;
    private javax.swing.JTextField P1_3_2_T4;
    private javax.swing.JPanel P1_3_3;
    private javax.swing.JLabel P1_3_3_L1;
    private javax.swing.JLabel P1_3_3_L2;
    private javax.swing.JLabel P1_3_3_L3;
    private javax.swing.JLabel P1_3_3_L4;
    private javax.swing.JLabel P1_3_3_L5;
    private javax.swing.JLabel P1_3_3_L6;
    private javax.swing.JTextField P1_3_3_T1;
    private javax.swing.JTextField P1_3_3_T2;
    private javax.swing.JTextField P1_3_3_T3;
    private javax.swing.JComboBox P1_3_C1;
    private javax.swing.JComboBox P1_3_C2;
    private javax.swing.JComboBox P1_3_C3;
    private javax.swing.JLabel P1_3_L1;
    private javax.swing.JLabel P1_3_L2;
    private javax.swing.JLabel P1_3_L3;
    private javax.swing.JRadioButton P1_3_R1;
    private javax.swing.JRadioButton P1_3_R2;
    private javax.swing.JLabel P1_3_STR;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField26;
    // End of variables declaration//GEN-END:variables
}
